# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 160fd6229db804c214e1bc485cc18f77610ae2ea300c3bd5f37f6e9dd5878bb8a033b307fa4ea8bb1b2580ce5e7bf0f2d51180055ae7f523b33df55ab085bef9

test:
  secret_key_base: bdabf949b1a9dc898a4df48ea4dfb798e896685890af62aee1704bfbb5752f83a70127d0be20b0ec527f02a2a7becbfd2ca3a21f2673ee6d4d2326afd3c5593e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
